argo-applications:
  project:
    - name: gl21-cube
      repoURL: https://github.com/yakiyoshi/devenv.git
      path:  gl21-cube
    - name: petclinic-stg
      repoURL: https://github.com/yakiyoshi/devenv.git
      path:  petclinic-stg