gogl-ci:
  project:
    # Specify OpenShift User
    users:
      - user01

  application:
    name: gl21-cube
    # Specify diretory stored application code in repogitory
    subdirectory: ./
    phrase: "1234567"

  staticanalysis:
    enabled: true

  appbuild:
    buildimage: quay.io/yakiyoshi/gogl:0.0.2

  imagebuild:
    baseimage: quay.io/yakiyoshi/jupyter-remote-desktop-proxy:virtgl-0.0.1

  deploy:
    gpu: true